baseurl: "https://www.gophercon.es/"
title: "Gophercon EU"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "GopherCon Europe"
  Description: "Conference description"
  Date: "30.05-01.06.2019"
  Venue: "Hard Rock Hotel"
  Address: ""
  City:  "Tenerife"
  State: "Spain"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "my-secret-maps-key"


  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - schedule
    - location
    - speakers
    - mc
    - cfp
    - diversityscholarship
   # - contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    schedule: "Schedule"
    location: "Location"
    cfp: "Call For Papers"
    speakers: "Speakers"
    mc: "MCs"
    diversityscholarship: "Diversity Scholarship"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register"
    link: "http://register.example.com"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  ForkButton:
    repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "Hugo"
      logo: "/img/hugo.png"
      url: "http://gohugo.io"

  # List of Partners
  Partners:
    - name: "Hugo"
      logo: "/img/hugo.jpg"
      url: "https://gohugo.io"
    - name: "BrazilJS"
      logo: "/img/partner.png"
      url: "http://braziljs.org"

  # The entire schedule
  Schedule:
    - name: "Workshops"
      time: "30.05"

    - name: "Talks track 1"
      time: "31.05"

    - name: "Talks track 2"
      time: "31.05"

    - name: "Community day"
      time: "01.06"


    - name: "Cassandra Salisbury"
      photo: "/img/speakers/cassandra.jpg"
      link:
        href: "https://twitter.com/cassandraoid"
        text: "@cassandraoid"
      presentation:
        title: ""
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: ""

  Mcs:
    - name: "Ashley McNamara"
      photo: "/img/mcs/host_Ashley-McNamara.jpg"
      link:
        href: "https://twitter.com/ashleymcnamara"
        text: "@ashleymcnamara"
    - name: "Steve Francia"
      photo: "/img/mcs/host_Steve-Francia.jpg"
      link:
        href: "https://twitter.com/spf13"
        text: "@spf13"
